name: Monorepo Deploy

on:
  push:
    branches:
      - main

jobs:
  frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Node.js for Frontend
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install Core Dependencies
        run: npm install

      - name: Build and Compile Frontend
        run: |
          cd frontend
          npm install
          npm run compile
          npm run build

      - name: Deploy Frontend to Heroku
        run: |
          echo "machine api.heroku.com login $HEROKU_EMAIL password $HEROKU_API_KEY" >> ~/.netrc
          echo "machine git.heroku.com login $HEROKU_EMAIL password $HEROKU_API_KEY" >> ~/.netrc
          heroku git:remote -a steve-kit-be
          git push heroku main

        env:
          APP_TO_START: "frontend"
          HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL }}
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

  backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Node.js for Backend
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install Core Dependencies
        run: npm install

      - name: Compile Backend
        run: |
          cd backend
          npm install
          npm run compile

      - name: Deploy Backend to Heroku
        run: |
          echo "machine api.heroku.com login $HEROKU_EMAIL password $HEROKU_API_KEY" >> ~/.netrc
          echo "machine git.heroku.com login $HEROKU_EMAIL password $HEROKU_API_KEY" >> ~/.netrc
          heroku git:remote -a steve-kit-be
          git push heroku main
        env:
          APP_TO_START: "backend"
          HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL }}
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
