name: Monorepo Deploy

on:
  push:
    branches:
      - main

jobs:
  frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js for Frontend
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install Frontend Dependencies
        run: cd frontend && npm install

      - name: Build and Compile Frontend
        run: |
          cd frontend
          npm run compile
          npm run build

      - name: Deploy Frontend to Heroku
        run: |
          echo "machine api.heroku.com login $HEROKU_EMAIL password $HEROKU_API_KEY" >> ~/.netrc
          echo "machine git.heroku.com login $HEROKU_EMAIL password $HEROKU_API_KEY" >> ~/.netrc
          git remote add heroku-frontend https://git.heroku.com/steve-kit-fe.git
          git push steve-kit-fe main
        env:
          HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL }}
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

  backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js for Backend
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install Backend Dependencies
        run: cd backend && npm install

      - name: Compile Backend
        run: |
          cd backend
          npm run compile

      - name: Deploy Backend to Heroku
        run: |
          echo "machine api.heroku.com login $HEROKU_EMAIL password $HEROKU_API_KEY" >> ~/.netrc
          echo "machine git.heroku.com login $HEROKU_EMAIL password $HEROKU_API_KEY" >> ~/.netrc
          git remote add heroku-backend https://git.heroku.com/steve-kit-be.git
          git push steve-kit-be main
        env:
          HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL }}
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
